sudo: false

notifications:
  email:
    on_success: never
    on_failure: never

language: php

php:
  - 7.1

cache:
  yarn: true
  directories:
    - node_modules
    - vendor

before_script:
  - if [[ ${NODE_ENABLED} == "true" ]]; then nvm install $(cat .nvmrc) && nvm use $(cat .nvmrc) && npm i -g yarn && yarn; fi
  - if [[ ${PHP_ENABLED} == "true" ]]; then composer install --dev --no-interaction && cp .env.example .env && php artisan key:generate; fi

script: bash -c "${TEST_SUITE}"

env:
  - PHP_ENABLED=true TEST_SUITE="./vendor/bin/phpunit --colors"
  - NODE_ENABLED=true TEST_SUITE="yarn test"
