language: node_js

services:
  - mysql

node_js:
  - 8.9

cache:
  directories:
    - node_modules

before_install:
  - mysql -e 'CREATE DATABASE nodetech_testing;'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - node_modules/.bin/istanbul report lcov json clover text
  - rm -rf coverage/client coverage/server
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

env:
  globals:
    - APP_SECRET=testing
    - TYPEORM_USERNAME=travis
    - NODE_ENV=testing
