export const FETCH_MANY_PLAYLISTS_REQUEST = 'playlist/FETCH_MANY_REQUEST';
export const FETCH_MANY_PLAYLISTS_SUCCESS = 'playlist/FETCH_MANY_SUCCESS';
export const FETCH_MANY_PLAYLISTS_FAILURE = 'playlist/FETCH_MANY_FAILURE';

export const FETCH_SINGLE_PLAYLIST_REQUEST = 'playlist/FETCH_SINGLE_REQUEST';
export const FETCH_SINGLE_PLAYLIST_SUCCESS = 'playlist/FETCH_SINGLE_SUCCESS';
export const FETCH_SINGLE_PLAYLIST_FAILURE = 'playlist/FETCH_SINGLE_FAILURE';

export const REMOVE_PLAYLIST_REQUEST = 'playlist/REMOVE_REQUEST';
export const REMOVE_PLAYLIST_SUCCESS = 'playlist/REMOVE_SUCCESS';
export const REMOVE_PLAYLIST_FAILURE = 'playlist/REMOVE_FAILURE';

export const SET_PLAYLIST = 'playlist/SET';
